"""creating relationships

Revision ID: 74fef2e756ff
Revises: 5c3680bbc606
Create Date: 2023-10-09 23:30:22.385513

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74fef2e756ff'
down_revision = '5c3680bbc606'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prescriber_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_appointments_prescriber_id_prescribers'), 'prescribers', ['prescriber_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_appointments_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_appointments_user_id_users'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_appointments_prescriber_id_prescribers'), type_='foreignkey')
        batch_op.drop_column('prescriber_id')

    # ### end Alembic commands ###
